language: python

cache: pip

script:
  ./350/build.sh

matrix:
  include:

    # Tests Python 3.6 on Ubuntu Trusty
    - python: 3.6
      dist: trusty
      sudo: true

    # Tests Python 3.6 and 3.7 on Ubuntu Xenial
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

